name: Running
on: [push]
jobs:
  build:
    name: Running
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run
        run: go run main.go
